### ISSUE TITLE
Batch-sync with the server, instead of uploading commands one by one.

### ISSUE THREAD

**Issue by NorfairKing** [NorfairKing/hastory#13]
@yigitozkavci

**Comment by StevenXL** [comment]
@NorfairKing I'd like to take this issue on. I'm responding here simply to let others know that I'm working on it. Let me think about implementation for a bit, propose it to you once I have a better idea, and then we can iterate on the proposal before I start coding.

**Comment by StevenXL** [comment]
@NorfairKing - Hi Syd. So here is what I am thinking in terms of implementation.

## Server

On the server, side:

1. Instead of accepting a single entry, the server should be updated so that it accepts a list of entries. Each entry is paired with the id that the client has assigned to the entry in its database. We'd update [SyncRequest](https://github.com/NorfairKing/hastory/blob/0af97aeb4219705cf13dae4940797bb526e3eb48/hastory-data/src/Data/Hastory/Types/SyncRequest.hs#L14):

```haskell
data SyncRequest =
  SyncRequest
    { syncRequestEntries :: [(EntryId, Entry)]
    , syncRequestHostName :: Text
    }
  deriving (Show, Eq, Generic)
```

2. Update the ["/entries" endpoint](https://github.com/NorfairKing/hastory/blob/13e4ca17bf4aa8479d8f41bad5871222f0d370bb/hastory-data/src/Data/Hastory/API.hs#L24) (it might get renamed) to return an association between the client's entry id and the servers' sync entry id rather than `NoContent`.

```haskell
type SyncResponse = [(EntryId, SyncEntryId)]
```

This will be atomic - either all entries get saved, or none do. If an entry already existed, then we will consider that a success and return the existing `SyncEntryId`. 

## Client

1. Update [Entry](https://github.com/NorfairKing/hastory/blob/ad9e8ff9551ae05f006ad0a9a2103771a2017fac/hastory-cli-data/src/Hastory/Cli/Data.hs#L28) so that one of its fields is a `ServerEntryId`, as proof that it has been sent to the server.

2. Update the [gather](https://github.com/NorfairKing/hastory/blob/13e4ca17bf4aa8479d8f41bad5871222f0d370bb/hastory-cli/src/Hastory/Cli/Commands/Gather.hs#L26) command (and the various configuration mechanism) so that it takes an extra argument, indicating if the settings is batch or not.

```haskell
data SyncSettings = Batch | Transactional

gather :: (MonadReader Settings m, MonadThrow m, MonadUnliftIO m) => SyncSettings m ()
gather = do
  text <- liftIO T.getContents
  gatherFrom text
```

3. Depending on the SyncSettings, [storeHistory]() will either save the entry locally and then send it to the sync server, or it will simply save the entry locally.

## How to Send in Batches

All of the above is fairly clear. Some small details might change, but conceptually I think those things are clear to me.

What is very unclear to me in the case of batching, what process takes care of looking into the local store, gathering up every item that has not been saved to the server.

### Approach #1 - Out-of-Band Batch Processing

Would I would like to do is to spin up a thread that checks the local store periodically, gathers up all the local entries that have not been sent to the server, and send them out of band. The problem that I see with this is that it doesn't seem to me that `hastory` is a daemon. This means that if I take this route, then we'd never send anything to the sync server because when a user types a command in their shell, it will save the command and the main program would exit.

### Approach #2 - In-Band Batch Processing

Another option is to have [storeHistory](https://github.com/NorfairKing/hastory/blob/13e4ca17bf4aa8479d8f41bad5871222f0d370bb/hastory-cli/src/Hastory/Cli/Commands/Gather.hs#L50) check its local store, and when it sees that the number of un-sync entries exceeds some threshold (or that the last entry that wasn't sync is "too old", for some definition of "too old"), it would then make the request to the sync server.

There are a number of downsides to this. The most obvious one is that we'd be doubling the amount of queries to the database on each `gather` invocation - once to store the entry, another time to check if we need to do a batch sync.

Secondly, a user typing commands into their terminal might see a delay when we send data to the server. (In fact, this might already be an issue, even in non-batch mode).

I'd love some guidance on how to solve this problem.

**Comment by NorfairKing** [comment]
First of all, I _love_ the design doc. This is exactly what people should be doing before implementing something. Take note, aspiring programmers.

You're right about all the tradeoffs you describe.
Here's what I have in mind to fix it:

* Never sync synchronously. In-band, as you call it. (My English isn't good enough what the right words are, but you get the point.)
* Have a `hastory sync` command that the user can set up to run periodically (using `cron` or `systemd` or so).

This is the way I do it with `intray` as well, but there it is optional.

Little comments on the rest:

> (or that the last entry that wasn't sync is "too old", for some definition of "too old"),

I don't think this is a good idea. We need to get all the commands.

> Update the gather command (and the various configuration mechanism) so that it takes an extra argument, indicating if the settings is batch or not.

I don't think this will be necessary, because we won't do any uploading in the gather command then.Update the "/entries" endpoint (it might get renamed) to return an association between the client's entry id and the servers' sync entry id rather than NoContent.

> Update the "/entries" endpoint (it might get renamed) to return an association between the client's entry id and the servers' sync entry id rather than NoContent.

Yes, but let's use a `Map` instead of a list of tuples.

**Comment by StevenXL** [comment]
@NorfairKing Thanks Syd for the suggestions. The idea of a separate program that can be ran via cron is a very elegant solution. I'll get stared on this and ping you on the next feedback request.

**Comment by StevenXL** [comment]
@NorfairKing I think we can close this issue, given the merge of #33.

**Comment by NorfairKing** [comment]
Jup!
