### ISSUE TITLE
Hastory Server - Allow Users to Pass in Connection String

### ISSUE THREAD

**Issue by StevenXL** [NorfairKing/hastory#43]
At the moment, there is [no way to configure](https://github.com/NorfairKing/hastory/blob/3714eb5ac0f4381656a05b45e190cf44b444c083/hastory-server/src/Hastory/Server.hs#L97) the database used by `hastory-server`. We should be able to configure this.

**Comment by NorfairKing** [comment]
> It seems like we don't use an XDG-compliant location for the server database. Should we do so?

I don't think so. Servers are not usually run in regular user accounts. I usually have the default database file be in the working dir.

> 1. Put in the infrastructure to allow the user to choose between SQLite and Postgres.

This would be the first time I do such a thing. It would be a good exercise, but keep in mind that I have no postgress instance anywhere.
This means that we would have to be able to run the code and the tests without a postgress installation, otherwise I can't maintain this code.

I recommend supporting only sqlite for now, and making postgress support a separate issue.

> I don't think we want foreign keys to be disabled in production, do we?

I think persistent migrations are broken if foreign keys are on. We should check.

**Comment by StevenXL** [comment]
@NorfairKing  I agree with all of your suggestions here. I think I am making this more complicated that I need. I'll be closing this down. Thank you.
