### ISSUE TITLE
Use Sqlite instead of json

### ISSUE THREAD

**Issue by NorfairKing** [NorfairKing/hastory#6]
The log files are currently in a custom format where each line is a json object.
This is a bad idea for many reasons.
Let's use sqlite instead.

**Comment by StevenXL** [comment]
@NorfairKing I'd love to give this a try as part of my Hacktoberfest contribution. I'm likely to get stuck on the implementation, but I would like to give this a try, get some code down, and then maybe ping you for help once I have gone down a specific implementation.

**Comment by NorfairKing** [comment]
Sounds good! I recommend using `persistent-sqlite`. If you get stuck, let me know and we can go over what you made together.

**Comment by StevenXL** [comment]
@NorfairKing Hi - I've created PR #9 to discuss. It is not ready, but I assume you'd like to see the diff. (There are a few fixes to make - such as putting bounds on the new dependencies, be more explicit in my imports, etc. - but I'd like to get the main PR functionality working).

The main idea that I am working on right now is making `Entry` a data type that is generated by `persistent`. 

The problem I ran into with this is that two fields in the original declaration of `Entity` do not have instances of `PersistField`. (`PersistField` is required in order to be able to save the data in the database). The fields in question are `workingDir :: Path` and `dateTime :: ZonedTime`.

I was able to declare an instance of `PersistField` for the `Path` data type - I wrapped it in a newtype `HastoryPath` to avoid orphaned instances. 

However, I am having a hard time implementing an instance of `PersistField` for `ZonedTime`. It looks like support for `ZonedTime` [was dropped in persistent](https://github.com/yesodweb/persistent/blob/master/docs/Persistent-entity-syntax.md). The closest thing that is supported is `UTCTime`, which already has an instance of `PersistField`. I was thinking of saving the `ZonedTime` as `UTCTime`, but unfortunately time zone information is lost, so I can't convert from `UTCTime` to `ZonedTime` when pulling the data out of the database.

How do you suggest we move forward here? We can either convert `Entry` to use `UTCTime` instead of `ZonedTime` (easiest I believe), or maybe we can store the data as text, since it seems that `ZonedTime` can be marshalled to / from text (given that there we are able to store it as JSON). 

Have I gone down the wrong path here?

**Comment by NorfairKing** [comment]
Hi! This is great already!

> (There are a few fixes to make
>
> - such as putting bounds on the new dependencies,

Don't bother, just get it to build with a given `stack.yaml`. This is an application, not a library.

> - be more explicit in my imports, etc.

Also: meh. If _I_, as anal as I am in reviews, don't care then you don't need to bother IMO.

> - but I'd like to get the main PR functionality working).

_This_ is the important bit. I'd rather you make something that works, and then make a second PR with nice extras afterwards.
I _do_ insist on testing though, but I can certainly help with that.

**Comment by StevenXL** [comment]
@NorfairKing Should we delete this issue?
